openapi: 3.0.0
info:
  title: Instructor Course API
  version: 1.0.0
  description: This is the Instructor Course API
paths:
  /api/v1/instructor/course/index:
    get:
      tags:
        - Instructor-Course
      operationId: getInstructorCourseIndex
      summary: "講師講座一覧を取得する。"
      responses:
        '200':
          description: 講座一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        course_id:
                          $ref: '../components/schemas/Course.yml#/CourseId'
                        title:
                          $ref: '../components/schemas/Course.yml#/Title'
                        image:
                          $ref: '../components/schemas/Course.yml#/Image'
                        status:
                          $ref: '../components/schemas/Course.yml#/Status'
  /api/v1/instructor/course/{course_id}:
    get:
      tags:
        - Instructor-Course
      operationId: getInstructorCourse
      summary: "講座の詳細情報を取得する。"
      parameters:
        - name: course_id
          in: path
          description: 講座テーブルの主キー
          required: true
          type: integer
      responses:
        '200':
          description: 講座詳細情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      course_id:
                        $ref: '../components/schemas/Course.yml#/CourseId'
                      title:
                        $ref: '../components/schemas/Course.yml#/Title'
                      image:
                        $ref: '../components/schemas/Course.yml#/Image'
                      status:
                        $ref: '../components/schemas/Course.yml#/Status'
                      chapters:
                        type: array
                        items:
                          type: object
                          properties:
                            chapter_id:
                              $ref: '../components/schemas/Chapter.yml#/ChapterId'
                            title:
                              $ref: '../components/schemas/Chapter.yml#/Title'
                            order:
                              $ref: '../components/schemas/Chapter.yml#/Order'
                            lessons:
                              type: array
                              items:
                                type: object
                                properties:
                                  lesson_id:
                                    $ref: '../components/schemas/Lesson.yml#/LessonId'
                                  title:
                                    $ref: '../components/schemas/Lesson.yml#/Title'
                                  url:
                                    $ref: '../components/schemas/Lesson.yml#/Url'
                                  remarks:
                                    $ref: '../components/schemas/Lesson.yml#/Remarks'
    post:
      tags:
        - Instructor-Course
      operationId: patchInstructorCourse
      summary: "講座情報を更新する。"
      parameters:
        - name: course_id
          in: path
          description: 講座テーブルの主キー
          required: true
          type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                  description: タイトル
                  example: '講座タイトル'
                status:
                  type: "string"
                  description: ステータス
                  example: 'public'
                image:
                  type: "file"
                  description: 画像ファイル
                  example: 'thumbnail.png'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                required:
                  - "result"
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
                  data:
                    type: object
                    properties:
                      course_id:
                        $ref: '../components/schemas/Course.yml#/CourseId'
                      title:
                        $ref: '../components/schemas/Course.yml#/Title'
                      image:
                        $ref: '../components/schemas/Course.yml#/Image'
                      status:
                        $ref: '../components/schemas/Course.yml#/Status'
    delete:
      tags:
        - Instructor-Course
      operationId: deleteInstructorCourse
      summary: "講座情報を削除する。"
      parameters:
        - name: course_id
          in: path
          description: 講座テーブルの主キー
          required: true
          type: integer
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                required:
                  - "result"
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
  /api/v1/instructor/course/{course_id}/edit:
    get:
      tags:
        - Instructor-Course
      operationId: getInstructorCourseEdit
      summary: "編集講座の情報を取得する。"
      parameters:
        - name: course_id
          in: path
          description: 講座テーブルの主キー
          required: true
          type: integer
      responses:
        '200':
          description: 講座詳細情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      course_id:
                        $ref: '../components/schemas/Course.yml#/CourseId'
                      title:
                        $ref: '../components/schemas/Course.yml#/Title'
                      image:
                        $ref: '../components/schemas/Course.yml#/Image'
                      status:
                        $ref: '../components/schemas/Course.yml#/Status'
  /api/v1/instructor/course:
    post:
      tags:
        - Instructor-Course
      operationId: postInstructorCourse
      summary: "講座情報を登録する。"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                  description: タイトル
                  example: '講座タイトル'
                image:
                  type: "file"
                  description: 画像ファイル
                  example: 'thumbnail.png'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                required:
                  - "result"
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
  /api/v1/instructor/course/{course_id}/attendance/status:
    get:
      tags:
        - Instructor-Course
      operationId: getInstructorCourseAttendanceStatus
      summary: "講座の受講状況を取得する。"
      parameters:
        - name: course_id
          in: path
          description: 講座テーブルの主キー
          required: true
          type: integer
      responses:
        '200':
          description: 講座受講状況
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        chapters:
                          type: array
                          items:
                            type: object
                            properties:
                              chapter_id:
                                $ref: '../components/schemas/Chapter.yml#/ChapterId'
                              title:
                                $ref: '../components/schemas/Chapter.yml#/Title'
                              completed_count:
                                type: integer
                                example: 1
  /api/v1/instructor/course/{course_id}/notification:
    post:
      tags:
        - Instructor-Course
      operationId: postInstructorCourseNotification
      summary: "講座のお知らせを登録する。"
      parameters:
        - name: course_id
          in: path
          description: 講座ID
          required: true
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - "title"
                - "body"
              type: "object"
              properties:
                title:
                  type: "string"
                  description: お知らせタイトル
                  example: 'レッスン「変数とは？」閲覧について'
                content:
                  type: "string"
                  description: 本文
                  example: '10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。'
                start_date:
                  type: "string"
                  description: お知らせ開始日
                  example: '2021-10-01 00:00:00'
                end_date:
                  type: "string"
                  description: お知らせ終了日
                  example: '2021-10-10 00:00:00'
                type:
                  type: "string"
                  description: お知らせタイプ
                  example: 'once'
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
  /api/v1/instructor/course/{course_id}/student/index:
    get:
      tags:
        - Instructor-Course
      operationId: getInstructorCourseStudentIndex
      summary: "講座の受講生一覧を取得する。"
      parameters:
        - name: course_id
          in: path
          description: 講座ID
          required: true
          type: integer
        - name: page
          in: query
          description: ページ番号
          required: false
          type: integer
        - name: per_page
          in: query
          description: 1ページあたりの表示件数
          required: false
          type: integer
        - name: sort_by
          in: query
          description: ソート対象
          required: false
          type: string
        - name: order
          in: query
          description: ソート順
          required: false
          type: string
      responses:
        '200':
          description: 講座受講生一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        course:
                          type: object
                          properties:
                            course_id:
                              $ref: '../components/schemas/Course.yml#/CourseId'
                            title:
                              $ref: '../components/schemas/Course.yml#/Title'
                            image:
                              $ref: '../components/schemas/Course.yml#/Image'
                        students:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                $ref: '../components/schemas/Student.yml#/StudentId'
                              nick_name:
                                $ref: '../components/schemas/Student.yml#/StudentNickName'
                              email:
                                $ref: '../components/schemas/Student.yml#/StudentEmail'
                              course_title:
                                $ref: '../components/schemas/Course.yml#/Title'
                              last_login_at:
                                $ref: '../components/schemas/Student.yml#/LastLoginAt'
                              attendanced_at:
                                $ref: '../components/schemas/Attendance.yml#/AttendancedAt'
                          pagination:
                            type: object
                            properties:
                              page:
                                type: integer
                                example: 1
                              total:
                                type: integer
                                example: 1
  /api/v1/instructor/course/status:
    put:
      tags:
        - Instructor-Course
      operationId: putInstructorCourseStatus
      summary: "講座のステータスを一括更新する。"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - "status"
              type: "object"
              properties:
                status:
                  type: "string"
                  description: ステータス
                  example: 'public'
