openapi: 3.0.0
info:
  title: Instructor Course API
  version: 1.0.0
  description: This is the Instructor Course API
paths:
  /api/v1/instructor/student/:
    post:
      tags:
        - Instructor-Student
      operationId: postInstructorStudent
      summary: "生徒情報を登録する。"
      requestBody:
        content:
          application/json:
            schema:
              required:
                - "given_name_by_instructor"
                - "email"
              type: "object"
              properties:
                given_name_by_instructor:
                  type: "string"
                  description: ユーザー名
                  example: 'ユーザー名'
                email:
                  type: "string"
                  description: メールアドレス
                  example: 'test@example.com'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
                  data:
                    type: "object"
                    properties:
                      student_id:
                        $ref: '../components/schemas/Student.yml#/StudentId'
                      given_name_by_instructor:
                        $ref: '../components/schemas/Student.yml#/GivenNameByInstructor'
                      email:
                        $ref: '../components/schemas/Student.yml#/StudentEmail'

  /api/v1/instructor/student/{student_id}:
    get:
      tags:
        - Instructor-Student
      operationId: getInstructorStudent
      summary: "生徒の詳細情報を取得する。"
      parameters:
        - name: student_id
          in: path
          description: 生徒テーブルの主キー
          required: true
          type: integer
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  data:
                    type: object
                    properties:
                      student_id:
                        $ref: '../components/schemas/Student.yml#/StudentId'
                      given_name_by_instructor:
                        $ref: '../components/schemas/Student.yml#/GivenNameByInstructor'
                      nick_name:
                        $ref: '../components/schemas/Student.yml#/StudentNickName'
                      last_name:
                        $ref: '../components/schemas/Student.yml#/LastName'
                      first_name:
                        $ref: '../components/schemas/Student.yml#/FirstName'
                      occupation:
                        $ref: '../components/schemas/Student.yml#/Occupation'
                      email:
                        $ref: '../components/schemas/Student.yml#/StudentEmail'
                      purpose:
                        $ref: '../components/schemas/Student.yml#/Purpose'
                      birth_date:
                        $ref: '../components/schemas/Student.yml#/BirthDate'
                      sex:
                        $ref: '../components/schemas/Student.yml#/Sex'
                      address:
                        $ref: '../components/schemas/Student.yml#/Address'
                      last_login_at:
                        $ref: '../components/schemas/Student.yml#/LastLoginAt'
