openapi: 3.0.0
info:
  title: Manager Lesson API
  version: 1.0.0
  description: This is the Manager Lesson API
paths:
  /api/v1/manager/course/{course_id}/chapter/{chapter_id}/lesson:
    post:
      tags:
        - Manager-Lesson
      operationId: storeManagerChapterLesson
      summary: "レッスン情報を登録する。"
      parameters:
        - name: course_id
          in: path
          description: 講座テーブルの主キー
          required: true
          type: integer
        - name: chapter_id
          in: path
          description: チャプターテーブルの主キー
          required: true
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                  description: タイトル
                  example: 'swaggerの書き方'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                required:
                  - "result"
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
                  data:
                    type: "object"
                    properties:
                      lesson_id:
                        $ref: '#../components/schemas/Lesson.yml#/LessonId'
                      title:
                        $ref: '#../components/schemas/Lesson.yml#/Title'
                      status:
                        $ref: '#../components/schemas/Lesson.yml#/Status'
                      order:
                        $ref: '#../components/schemas/Lesson.yml#/Order'
  /api/v1/manager/course/{course_id}/chapter/{chapter_id}/lesson/{lesson_id}:
    put:
      tags:
        - Manager-Lesson
      operationId: putManagerChapterLesson
      summary: "レッスン情報を更新する。"
      parameters:
        - name: course_id
          in: path
          description: 講座テーブルの主キー
          required: true
          type: integer
        - name: chapter_id
          in: path
          description: チャプターテーブルの主キー
          required: true
          type: integer
        - name: lesson_id
          in: path
          description: レッスンテーブルの主キー
          required: true
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                  description: タイトル
                  example: 'レッスンタイトル'
                url:
                  type: "string"
                  description: URL
                  example: 'https://www.youtube.com/watch?v=xxxxxxxxxxx'
                remarks:
                  type: "string"
                  description: 備考
                  example: '備考'
                status:
                  type: "string"
                  description: ステータス
                  example: 'public'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                required:
                  - "result"
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
    delete:
      tags:
        - Manager-Lesson
      operationId: deleteManagerChapterLesson
      summary: "レッスン情報を削除する。"
      parameters:
        - name: course_id
          in: path
          description: 講座テーブルの主キー
          required: true
          type: integer
        - name: chapter_id
          in: path
          description: チャプターテーブルの主キー
          required: true
          type: integer
        - name: lesson_id
          in: path
          description: レッスンテーブルの主キー
          required: true
          type: integer
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                required:
                  - "result"
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
  /api/v1/manager/course/{course_id}/chapter/{chapter_id}/lesson/sort:
    post:
      tags:
        - Manager-Lesson
      operationId: sortManagerChapterLesson
      summary: "レッスン情報の並び順を更新する。"
      parameters:
        - name: course_id
          in: path
          description: 講座テーブルの主キー
          required: true
          type: integer
        - name: chapter_id
          in: path
          description: チャプターテーブルの主キー
          required: true
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                lessons:
                  type: "array"
                  description: レッスンの配列
                  items:
                    type: "object"
                    properties:
                      lesson_id:
                        $ref: '#../components/schemas/Lesson.yml#/LessonId'
                      order:
                        $ref: '#../components/schemas/Lesson.yml#/Order'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
