openapi: 3.0.0
info:
  title: Student API
  version: 1.0.0
paths:
  # お知らせ
  /api/v1/notification:
    get:
      tags:
        - Notification
      operationId: getNotification
      summary: "お知らせ一覧を取得する。"
      responses:
        '200':
          description: お知らせ一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        notification_id:
                          $ref: '../components/schemas/Notification.yml#/NotificationId'
                        course_id:
                          $ref: '../components/schemas/Course.yml#/CourseId'
                        course_title:
                          $ref: '../components/schemas/Course.yml#/Title'
                        title:
                          $ref: '../components/schemas/Notification.yml#/Title'
                        content:
                          $ref: '../components/schemas/Notification.yml#/Content'
                        type:
                          $ref: '../components/schemas/Notification.yml#/Type'
