openapi: 3.0.0
info:
  title: Student Attendance
  version: 1.0.0
  description: This is the Student Attendance API
paths:
  /api/v1/attendance/index:
    get:
      tags:
        - Student-Attendance
      operationId: getAttendanceIndex
      summary: "受講中の講座一覧を取得する。"
      parameters:
        - name: search_word
          in: query
          description: 検索ワード
          required: false
          type: string
      responses:
        '200':
          description: 受講一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        attendance_id:
                          $ref: '../components/schemas/Attendance.yml#/AttendanceId'
                        progress:
                          $ref: '../components/schemas/Attendance.yml#/Progress'
                        course:
                          type: object
                          properties:
                            course_id:
                              $ref: '../components/schemas/Course.yml#/CourseId'
                            title:
                              $ref: '../components/schemas/Course.yml#/Title'
                            image:
                              $ref: '../components/schemas/Course.yml#/Image'
                            instructor:
                              type: object
                              properties:
                                instructor_id:
                                  $ref: '../components/schemas/Instructor.yml#/InstructorId'
                                nick_name:
                                  $ref: '../components/schemas/Instructor.yml#/NickName'
                                last_name:
                                  $ref: '../components/schemas/Instructor.yml#/LastName'
                                first_name:
                                  $ref: '../components/schemas/Instructor.yml#/FirstName'
                                email:
                                  $ref: '../components/schemas/Instructor.yml#/Email'
  /api/v1/attendance/{attendance_id}:
    get:
      tags:
        - Student-Attendance
      operationId: getAttendance
      summary: "受講中の講座の詳細情報を取得する。"
      parameters:
        - name: attendance_id
          in: path
          description: 受講テーブルの主キー
          required: true
          type: integer
      responses:
        '200':
          description: 受講詳細情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      attendance_id:
                        $ref: '../components/schemas/Attendance.yml#/AttendanceId'
                      progress:
                        $ref: '../components/schemas/Attendance.yml#/Progress'
                      course:
                        type: object
                        properties:
                          course_id:
                            $ref: '../components/schemas/Course.yml#/CourseId'
                          title:
                            $ref: '../components/schemas/Course.yml#/Title'
                          image:
                            $ref: '../components/schemas/Course.yml#/Image'
                          instructor:
                            type: object
                            properties:
                              instructor_id:
                                $ref: '../components/schemas/Instructor.yml#/InstructorId'
                              nick_name:
                                $ref: '../components/schemas/Instructor.yml#/NickName'
                              last_name:
                                $ref: '../components/schemas/Instructor.yml#/LastName'
                              first_name:
                                $ref: '../components/schemas/Instructor.yml#/FirstName'
                              email:
                                $ref: '../components/schemas/Instructor.yml#/Email'
                          chapters:
                            type: array
                            items:
                              type: object
                              properties:
                                chapter_id:
                                  $ref: '../components/schemas/Chapter.yml#/ChapterId'
                                title:
                                  $ref: '../components/schemas/Chapter.yml#/Title'
                                lessons:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      lesson_id:
                                        $ref: '../components/schemas/Lesson.yml#/LessonId'
                                      title:
                                        $ref: '../components/schemas/Lesson.yml#/Title'
                                      url:
                                        $ref: '../components/schemas/Lesson.yml#/Url'
                                      remarks:
                                        $ref: '../components/schemas/Lesson.yml#/Remarks'
                                      lesson_attendance:
                                        type: object
                                        properties:
                                          lesson_attendance_id:
                                            $ref: '../components/schemas/LessonAttendance.yml#/LessonAttendanceId'
                                          status:
                                            $ref: '../components/schemas/LessonAttendance.yml#/Status'
  /api/v1/attendance/{attendance_id}/progress:
    get:
      tags:
        - Student-Attendance
      operationId: getAttendanceProgress
      summary: "受講中の講座の進捗率を取得する。"
      parameters:
        - name: course_id
          in: path
          description: 講座テーブルの主キー
          required: true
          type: integer
      responses:
        '200':
          description: 講座進捗率
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      course:
                        type: object
                        properties:
                          course_id:
                            $ref: '../components/schemas/Course.yml#/CourseId'
                          progress:
                            type: integer
                            example: 10
                      number_of_completed_chapters:
                        type: integer
                        example: 1
                      number_of_total_chapters:
                        type: integer
                        example: 3
                      number_of_completed_lessons:
                        type: integer
                        example: 2
                      number_of_total_lessons:
                        type: integer
                        example: 6
                      continue_lesson:
                        type: object
                        properties:
                          chapter_id:
                            $ref: '../components/schemas/Chapter.yml#/ChapterId'
                          lesson_id:
                            $ref: '../components/schemas/Lesson.yml#/LessonId'
