openapi: 3.0.0
info:
  title: Student API
  version: 1.0.0
paths:
  /api/v1/student/:
    post:
      tags:
        - Student
      operationId: storeStudent
      summary: "生徒情報を登録する。"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nick_name:
                  type: string
                  description: ニックネーム
                  example: 'ニックネーム'
                last_name:
                  type: string
                  description: 姓
                  example: '名字'
                first_name:
                  type: string
                  description: 名
                  example: '名前'
                occupation:
                  type: string
                  description: 職業
                  example: 'エンジニア'
                purpose:
                  type: string
                  description: 目的
                  example: 'スキルアップのため'
                email:
                  type: string
                  description: メールアドレス
                  example: 'test@example.com'
                birth_date:
                  type: string
                  description: 生年月日
                  example: '2022-10-17'
                sex:
                  type: string
                  description: 性別
                  example: 'woman'
                address:
                  type: string
                  description: 住所
                  example: '東京都'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      nick_name:
                        $ref: '../components/schemas/Student.yml#/StudentNickName'
                      last_name:
                        $ref: '../components/schemas/Student.yml#/LastName'
                      first_name:
                        $ref: '../components/schemas/Student.yml#/FirstName'
                      occupation:
                        $ref: '../components/schemas/Student.yml#/Occupation'
                      purpose:
                        $ref: '../components/schemas/Student.yml#/Purpose'
                      email:
                        $ref: '../components/schemas/Student.yml#/StudentEmail'
                      birth_date:
                        $ref: '../components/schemas/Student.yml#/BirthDate'
                      sex:
                        $ref: '../components/schemas/Student.yml#/Sex'
                      address:
                        $ref: '../components/schemas/Student.yml#/Address'
  /api/v1/student/update:
    post:
      tags:
        - Student
      operationId: patchStudent
      summary: "生徒情報を更新する。"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nick_name:
                  type: string
                  description: ニックネーム
                  example: 'ニックネーム'
                last_name:
                  type: string
                  description: 姓
                  example: '姓'
                first_name:
                  type: string
                  description: 名
                  example: '名'
                occupation:
                  type: string
                  description: 職業
                  example: '職業'
                purpose:
                  type: string
                  description: 目的
                  example: '目的'
                email:
                  type: string
                  description: メールアドレス
                  example: 'test@example.com'
                birth_date:
                  type: string
                  description: 生年月日
                  example: '2022-10-17'
                sex:
                  type: string
                  description: 性別
                  example: 'man'
                address:
                  type: string
                  description: 住所
                  example: '住所'
                profile_image:
                  type: file
                  description: プロフィール画像
                  example: 'profile.png'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      nick_name:
                        $ref: '../components/schemas/Student.yml#/StudentNickName'
                      last_name:
                        $ref: '../components/schemas/Student.yml#/LastName'
                      first_name:
                        $ref: '../components/schemas/Student.yml#/FirstName'
                      occupation:
                        $ref: '../components/schemas/Student.yml#/Occupation'
                      purpose:
                        $ref: '../components/schemas/Student.yml#/Purpose'
                      email:
                        $ref: '../components/schemas/Student.yml#/StudentEmail'
                      birth_date:
                        $ref: '../components/schemas/Student.yml#/BirthDate'
                      sex:
                        $ref: '../components/schemas/Student.yml#/Sex'
                      address:
                        $ref: '../components/schemas/Student.yml#/Address'
                      profile_image:
                        $ref: '../components/schemas/Student.yml#/StudentProfileImage'
  /api/v1/student/edit:
    get:
      tags:
        - Student
      operationId: getStudent
      summary: "生徒情報を取得する。"
      responses:
        '200':
          description: 生徒情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      student_id:
                        $ref: '../components/schemas/Student.yml#/StudentId'
                      nick_name:
                        $ref: '../components/schemas/Student.yml#/StudentNickName'
                      last_name:
                        $ref: '../components/schemas/Student.yml#/LastName'
                      first_name:
                        $ref: '../components/schemas/Student.yml#/FirstName'
                      occupation:
                        $ref: '../components/schemas/Student.yml#/Occupation'
                      purpose:
                        $ref: '../components/schemas/Student.yml#/Purpose'
                      email:
                        $ref: '../components/schemas/Student.yml#/StudentEmail'
                      birth_date:
                        $ref: '../components/schemas/Student.yml#/BirthDate'
                      sex:
                        $ref: '../components/schemas/Student.yml#/Sex'
                      address:
                        $ref: '../components/schemas/Student.yml#/Address'
                      profile_image:
                        $ref: '../components/schemas/Student.yml#/StudentProfileImage'

