openapi: 3.0.0
info:
  title: Instructor API
  version: 1.0.0
  description: This is the Instructor API
paths:
  /api/v1/instructor:
    post:
      tags:
        - Instructor
      operationId: updateInstructor
      summary: 講師情報を更新する。
      description: |
        講師情報を更新する。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nick_name:
                  type: string
                  description: ニックネーム
                  example: ニックネーム
                last_name:
                  type: string
                  description: 名字
                  example: 名字
                first_name:
                  type: string
                  description: 名前
                  example: 名前
                email:
                  type: string
                  description: メールアドレス
                  example: test@example.com
                profile_image:
                  type: string
                  description: プロフィール画像
                  example: /instructor/xxx.png
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                required:
                  - result
                type: object
                properties:
                  result:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      nick_name:
                        $ref: '#/paths/~1api~1v1~1instructor/post/requestBody/content/application~1json/schema/properties/nick_name'
                      last_name:
                        $ref: '#/paths/~1api~1v1~1instructor/post/requestBody/content/application~1json/schema/properties/last_name'
                      first_name:
                        $ref: '#/paths/~1api~1v1~1instructor/post/requestBody/content/application~1json/schema/properties/first_name'
                      email:
                        $ref: '#/paths/~1api~1v1~1instructor/post/requestBody/content/application~1json/schema/properties/email'
                      profile_image:
                        $ref: '#/paths/~1api~1v1~1instructor/post/requestBody/content/application~1json/schema/properties/profile_image'
  /api/v1/Instructor.yml#/edit:
    get:
      tags:
        - Instructor
      operationId: getInstructor
      summary: 講師情報を取得する。
      responses:
        '200':
          description: 講師情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      instructor_id:
                        type: integer
                        description: 講師テーブル主キー
                        example: 1
                      nick_name:
                        $ref: '#/paths/~1api~1v1~1instructor/post/requestBody/content/application~1json/schema/properties/nick_name'
                      last_name:
                        $ref: '#/paths/~1api~1v1~1instructor/post/requestBody/content/application~1json/schema/properties/last_name'
                      first_name:
                        $ref: '#/paths/~1api~1v1~1instructor/post/requestBody/content/application~1json/schema/properties/first_name'
                      email:
                        $ref: '#/paths/~1api~1v1~1instructor/post/requestBody/content/application~1json/schema/properties/email'
                      profile_image:
                        $ref: '#/paths/~1api~1v1~1instructor/post/requestBody/content/application~1json/schema/properties/profile_image'
