openapi: 3.0.0
info:
  title: Instructor Course API
  version: 1.0.0
  description: This is the Instructor Course API
paths:
  /api/v1/instructor/notification/index:
    get:
      tags:
        - Instructor-Notification
      operationId: getInstructorNotificationIndex
      summary: お知らせ一覧を取得する。
      responses:
        '200':
          description: お知らせ一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        notifications:
                          type: array
                          items:
                            type: object
                            properties:
                              notification_id:
                                $ref: '#/paths/~1api~1v1~1instructor~1notification~1%7Bnotification_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/notification_id'
                              title:
                                $ref: '#/paths/~1api~1v1~1instructor~1notification~1%7Bnotification_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/title'
                              content:
                                $ref: '#/paths/~1api~1v1~1instructor~1notification~1%7Bnotification_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/content'
                              start_date:
                                $ref: '#/paths/~1api~1v1~1instructor~1notification~1%7Bnotification_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/start_date'
                              end_date:
                                $ref: '#/paths/~1api~1v1~1instructor~1notification~1%7Bnotification_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/end_date'
                              type:
                                $ref: '#/paths/~1api~1v1~1instructor~1notification~1%7Bnotification_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/type'
                        pagination:
                          type: object
                          properties:
                            page:
                              type: integer
                              description: ページ番号
                              example: 1
                            total:
                              type: integer
                              description: ページ総数
                              example: 1
  '/api/v1/instructor/notification/{notification_id}':
    get:
      tags:
        - Instructor-Notification
      operationId: getInstructorNotification
      summary: お知らせの詳細情報を取得する。
      parameters:
        - name: notification_id
          in: path
          description: お知らせテーブルの主キー
          required: true
          type: integer
      responses:
        '200':
          description: お知らせ詳細情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      notification_id:
                        type: integer
                        description: お知らせテーブルの主キー
                        example: 1
                      couse_id:
                        type: integer
                        description: 講座テーブル主キー
                        example: 1
                      title:
                        type: string
                        description: お知らせタイトル
                        example: レッスン「変数とは？」閲覧について
                      content:
                        type: string
                        description: 本文
                        example: 10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。
                      start_date:
                        type: string
                        description: 開始日
                        example: '2022/10/17 00:00:00'
                      end_date:
                        type: string
                        description: 終了日
                        example: '2022/11/17 00:00:00'
                      type:
                        type: string
                        description: 表示区分（一度だけ表示、毎回表示）
                        example: once
    patch:
      tags:
        - Instructor-Notification
      operationId: patchInstructorNotification
      summary: お知らせ情報を更新する。
      parameters:
        - name: notification_id
          in: path
          description: お知らせテーブルの主キー
          required: true
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - title
                - content
                - start_date
                - end_date
                - type
              type: object
              properties:
                title:
                  type: string
                  description: お知らせタイトル
                  example: レッスン「変数とは？」閲覧について
                content:
                  type: string
                  description: 本文
                  example: 10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。
                start_date:
                  type: string
                  description: お知らせ開始日
                  example: '2021-10-01 00:00:00'
                end_date:
                  type: string
                  description: お知らせ終了日
                  example: '2021-10-10 00:00:00'
                type:
                  type: string
                  description: お知らせタイプ
                  example: once
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      title:
                        $ref: '#/paths/~1api~1v1~1instructor~1notification~1%7Bnotification_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/title'
                      content:
                        $ref: '#/paths/~1api~1v1~1instructor~1notification~1%7Bnotification_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/content'
                      start_date:
                        $ref: '#/paths/~1api~1v1~1instructor~1notification~1%7Bnotification_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/start_date'
                      end_date:
                        $ref: '#/paths/~1api~1v1~1instructor~1notification~1%7Bnotification_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/end_date'
                      type:
                        $ref: '#/paths/~1api~1v1~1instructor~1notification~1%7Bnotification_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/type'
