openapi: 3.0.0
info:
  title: Manager Course API
  version: 1.0.0
  description: This is the Manager Course API
paths:
  /api/v1/manager/course/index:
    get:
      tags:
        - Manager-Course
      operationId: getManagerCourseIndex
      summary: 講師講座一覧を取得する。
      responses:
        '200':
          description: 講座一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        course_id:
                          $ref: '#/paths/~1api~1v1~1manager~1course~1%7Bcourse_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/course_id'
                        title:
                          $ref: '#/paths/~1api~1v1~1manager~1course~1%7Bcourse_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/title'
                        image:
                          $ref: '#/paths/~1api~1v1~1manager~1course~1%7Bcourse_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/image'
                        status:
                          $ref: '#/paths/~1api~1v1~1manager~1course~1%7Bcourse_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/status'
  '/api/v1/manager/course/{course_id}':
    get:
      tags:
        - Manager-Course
      operationId: getManagerCourse
      summary: 講座の詳細情報を取得する。
      parameters:
        - name: course_id
          in: path
          description: 講座テーブルの主キー
          required: true
          type: integer
      responses:
        '200':
          description: 講座詳細情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      course_id:
                        type: integer
                        description: 講座テーブル主キー
                        example: 1
                      title:
                        type: string
                        description: 講座名
                        example: PHP入門講座
                      image:
                        type: string
                        description: 講座サムネイル画像ファイルパス
                        example: /course/xxx.png
                      status:
                        type: string
                        description: 講座ステータス
                        example: public
                      chapters:
                        type: array
                        items:
                          type: object
                          properties:
                            chapter_id:
                              type: integer
                              description: チャプターテーブルの主キー
                              example: 1
                            title:
                              type: string
                              description: チャプタータイトル
                              example: Hello Worldを出力する
                            order:
                              type: integer
                              description: 順番
                              example: 1
                            lessons:
                              type: array
                              items:
                                type: object
                                properties:
                                  lesson_id:
                                    type: integer
                                    description: レッスンテーブルの主キー
                                    example: 1
                                  title:
                                    type: string
                                    description: レッスン名
                                    example: swaggerの書き方
                                  url:
                                    type: string
                                    description: 教材動画URL
                                    example: 'http::www.youtube'
                                  remarks:
                                    type: string
                                    description: 備考欄
                                    example: 動画index
    post:
      tags:
        - Manager-Course
      operationId: postManagerCourse
      summary: 講座情報を更新する。
      parameters:
        - name: course_id
          in: path
          description: 講座テーブルの主キー
          required: true
          type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: タイトル
                  example: 講座タイトル
                status:
                  type: string
                  description: ステータス
                  example: public
                image:
                  type: file
                  description: 画像ファイル
                  example: thumbnail.png
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                required:
                  - result
                type: object
                properties:
                  result:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      course_id:
                        $ref: '#/paths/~1api~1v1~1manager~1course~1%7Bcourse_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/course_id'
                      title:
                        $ref: '#/paths/~1api~1v1~1manager~1course~1%7Bcourse_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/title'
                      image:
                        $ref: '#/paths/~1api~1v1~1manager~1course~1%7Bcourse_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/image'
                      status:
                        $ref: '#/paths/~1api~1v1~1manager~1course~1%7Bcourse_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/status'
    delete:
      tags:
        - Manager-Course
      operationId: deleteManagerCourse
      summary: 講座情報を削除する。
      parameters:
        - name: course_id
          in: path
          description: 講座テーブルの主キー
          required: true
          type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                required:
                  - result
                type: object
                properties:
                  result:
                    type: boolean
                    example: true
  /api/v1/manager/course:
    post:
      tags:
        - Manager-Course
      operationId: postManagerCourse
      summary: 講座情報を登録する。
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: タイトル
                  example: 講座タイトル
                image:
                  type: file
                  description: 画像ファイル
                  example: thumbnail.png
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                required:
                  - result
                type: object
                properties:
                  result:
                    type: boolean
                    example: true
  '/api/v1/manager/course/{course_id}/attendance/status':
    get:
      tags:
        - Manager-Course
      operationId: getManagerCourseAttendanceStatus
      summary: 講座の受講状況を取得する。
      parameters:
        - name: course_id
          in: path
          description: 講座テーブルの主キー
          required: true
          type: integer
      responses:
        '200':
          description: 講座受講状況
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        chapters:
                          type: array
                          items:
                            type: object
                            properties:
                              chapter_id:
                                $ref: '#/paths/~1api~1v1~1manager~1course~1%7Bcourse_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/chapters/items/properties/chapter_id'
                              title:
                                $ref: '#/paths/~1api~1v1~1manager~1course~1%7Bcourse_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/chapters/items/properties/title'
                              completed_count:
                                type: integer
                                example: 1
  '/api/v1/manager/course/{course_id}/notification':
    post:
      tags:
        - Manager-Course
      operationId: postManagerCourseNotification
      summary: 講座のお知らせを登録する。
      parameters:
        - name: course_id
          in: path
          description: 講座ID
          required: true
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - title
                - body
              type: object
              properties:
                title:
                  type: string
                  description: お知らせタイトル
                  example: レッスン「変数とは？」閲覧について
                content:
                  type: string
                  description: 本文
                  example: 10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。
                start_date:
                  type: string
                  description: お知らせ開始日
                  example: '2021-10-01 00:00:00'
                end_date:
                  type: string
                  description: お知らせ終了日
                  example: '2021-10-10 00:00:00'
                type:
                  type: string
                  description: お知らせタイプ
                  example: once
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    example: true
  '/api/v1/manager/course/{course_id}/student/index':
    get:
      tags:
        - Manager-Course
      operationId: getManagerCourseStudentIndex
      summary: 講座の受講生一覧を取得する。
      parameters:
        - name: course_id
          in: path
          description: 講座ID
          required: true
          type: integer
        - name: page
          in: query
          description: ページ番号
          required: false
          type: integer
        - name: per_page
          in: query
          description: 1ページあたりの表示件数
          required: false
          type: integer
        - name: sort_by
          in: query
          description: ソート対象
          required: false
          type: string
        - name: order
          in: query
          description: ソート順
          required: false
          type: string
        - name: inputText
          in: query
          description: 検索文字列
          required: false
          type: integer
        - name: startDate
          in: query
          description: 日付検索開始日
          required: false
          type: integer
        - name: endDate
          in: query
          description: 日付検索終了日
          required: false
          type: integer
      responses:
        '200':
          description: 講座受講生一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        course:
                          type: object
                          properties:
                            course_id:
                              $ref: '#/paths/~1api~1v1~1manager~1course~1%7Bcourse_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/course_id'
                            title:
                              $ref: '#/paths/~1api~1v1~1manager~1course~1%7Bcourse_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/title'
                            image:
                              $ref: '#/paths/~1api~1v1~1manager~1course~1%7Bcourse_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/image'
                        pagination:
                          type: object
                          properties:
                            page:
                              type: integer
                              example: 1
                            total:
                              type: integer
                              example: 1
                        students:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                description: 生徒テーブル主キー
                                example: 1
                              nick_name:
                                type: string
                                description: ニックネーム
                                example: ニックネーム
                              email:
                                type: string
                                description: メールアドレス
                                example: test@example.com
                              course_title:
                                $ref: '#/paths/~1api~1v1~1manager~1course~1%7Bcourse_id%7D/get/responses/200/content/application~1json/schema/properties/data/properties/title'
                              last_login_at:
                                type: string
                                description: 最終ログイン日時
                                example: '2022/10/17 00:00:00'
                              attendanced_at:
                                type: string
                                description: 受講日時
                                example: 2022/10/17
  /api/v1/manager/course/status:
    put:
      tags:
        - Manager-Course
      operationId: putManagerCourseStatus
      summary: 講座のステータスを一括更新する。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - status
              type: object
              properties:
                status:
                  type: string
                  description: ステータス
                  example: public
