openapi: 3.0.0
info:
  title: Student API
  version: 1.0.0
paths:
  /api/v1/notification:
    get:
      tags:
        - Notification
      operationId: getNotification
      summary: お知らせ一覧を取得する。
      responses:
        '200':
          description: お知らせ一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: お知らせテーブルの主キー
                          example: 1
                        course_id:
                          type: integer
                          description: 講座テーブル主キー
                          example: 1
                        course_title:
                          type: string
                          description: 講座名
                          example: PHP入門講座
                        title:
                          type: string
                          description: お知らせタイトル
                          example: レッスン「変数とは？」閲覧について
                        content:
                          type: string
                          description: 本文
                          example: 10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。
                        type:
                          type: string
                          description: 表示区分（一度だけ表示、毎回表示）
                          example: once
