openapi: 3.0.0
info:
  version: 1.0.0
  title: 受講管理アプリ API
servers:
  - url: 'http://localhost:8080/api'
paths:
  /v1/course/index:
    get:
      tags:
        - student-course
      operationId: getCourseIndex
      summary: "受講講座情報の一覧を取得する。"
      description: >
        受講者IDから、受講講座の一覧情報を取得する。
      security: 
        - Bearer: []
      parameters:
        - name: student_id
          in: query
          description: 受講者テーブル主キー
          required: true
          type: int
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      responses:
        '200':
          description: 受講講座一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      allOf:
                        - $ref: '#/components/schemas/Course'
                        - type: "object"
                          properties:
                            attendance:
                              $ref: '#/components/schemas/Attendance'
                            instructor:
                              $ref: '#/components/schemas/Instructor'
  /v1/course:
    get:
      tags:
        - student-course
      operationId: getCourse
      summary: "受講講座の詳細情報を取得する。"
      description: >
        受講者IDを指定して、受講講座の詳細情報を取得する。
      security:
        -Bearer: []
      parameters:
        - name: attendance_id
          in: query
          description: 受講テーブルの主キー
          required: true
          type: int
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      responses:
        '200':
          description: 講座詳細情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  data: 
                    allOf:
                      - $ref: '#/components/schemas/Course'
                      - type: object
                        properties:
                          instructor:
                            $ref: '#/components/schemas/Instructor'
                          attendance:
                            $ref: '#/components/schemas/Attendance'
                      - type: object
                        properties:
                          chapters:
                            type: array
                            items:
                              allOf:
                                - $ref: '#/components/schemas/Chapter'
                                - type: object
                                  properties:
                                    lessons:
                                      type: array
                                      items:
                                        allOf:
                                          - $ref: '#/components/schemas/Lesson'
                                          - type: object
                                            properties:
                                              lesson_attendance:
                                                $ref: '#/components/schemas/LessonAttendance'
  /v1/course/chapter:
    get:
      tags:
        - student-course
      operationId: getChapter
      summary: "受講講座のチャプターの詳細情報を取得する。"
      description: >
        チャプターIDと受講IDを指定して、チャプター詳細情報を参照する。
      security:
        -Bearer: []
      parameters:
        - name: chapter_id
          in: query
          description: チャプターテーブルの主キー
          required: true
          type: int
        - name: attendance_id
          in: query
          description: 受講テーブルの主キー
          required: true
          type: int
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      responses:
        '200':
          description: チャプター詳細情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    allOf:
                      - $ref: '#/components/schemas/Chapter'
                      - type: object
                        properties:
                          lessons:
                            type: array
                            items:
                              allOf:
                                - $ref: '#/components/schemas/Lesson'
                                - type: object
                                  properties:
                                    lesson_attendance:
                                      $ref: '#/components/schemas/LessonAttendance'
  /v1/lesson-attendance:
    patch:
      tags:
        - lesson-attendance
      operationId: patchLessonAttendance
      summary: "レッスン受講状態更新"
      description: >
        レッスン受講状態IDと状態を指定して、レッスン受講状態を更新する
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - "lesson_attendance_id"
                - "status"
              type: "object"
              properties:
                lesson_attendance_id:
                  type: "int"
                  description: レッスン受講状態ID
                  example: 1
                status:
                  type: "string"
                  description: 状態(受講前、受講中、受講完了)
                  example: 'in_attendance'
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                required:
                  - "result"
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
  /v1/instructor/course/index:
    get:
      tags:
        - instructor-course
      operationId: getInstructorCourseIndex
      summary: "講師講座一覧参照"
      description: >
        講師IDを指定して、講座一覧情報を取得する
      security: 
        - Bearer: []
      parameters:
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      responses:
        '200':
          description: 講座一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      allOf:
                        - $ref: '#/components/schemas/Course'
  /v1/instructor/course/{course_id}:
    get:
      tags:
        - instructor-course
      operationId: getInstructorCourse
      summary: "講座の詳細情報を取得する。"
      description: >
        講座の詳細情報を取得する。
      security:
        -Bearer: []
      parameters:
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      responses:
        '200':
          description: 講座詳細情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  data: 
                    allOf:
                      - $ref: '#/components/schemas/Course'
                      - type: object
                        properties:
                          chapters:
                            type: array
                            items:
                              allOf:
                                - $ref: '#/components/schemas/Chapter'
                                - type: object
                                  properties:
                                    lessons:
                                      type: array
                                      items:
                                        allOf:
                                          - $ref: '#/components/schemas/Lesson'
    post:
      tags:
        - instructor-course
      operationId: patchInstructorCourse
      summary: "講座情報を更新する。"
      description: >
        講座情報を更新する。
      security:
        -Bearer: []
      parameters:
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                  description: タイトル
                  example: '講座タイトル'
                image:
                  type: "file"
                  description: 画像ファイル
                  example: 'thumbnail.png'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                required:
                  - "result"
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
                  data: 
                    allOf:
                      - $ref: '#/components/schemas/Course'
    delete:
      tags:
        - instructor-course
      operationId: deleteInstructorCourse
      summary: "講座情報を削除する。"
      description: >
        講座情報を削除する。
      security:
        -Bearer: []
      parameters:
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                required:
                  - "result"
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
  /v1/instructor/course/{course_id}/edit:
    get:
      tags:
        - instructor-course
      operationId: getInstructorCourseEdit
      summary: "編集講座の情報を取得する。"
      description: >
        編集講座の情報を取得する。
      security:
        -Bearer: []
      parameters:
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      responses:
        '200':
          description: 講座詳細情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  data: 
                    allOf:
                      - $ref: '#/components/schemas/Course'
  /v1/instructor/course:
    post:
      tags:
        - instructor-course
      operationId: postInstructorCourse
      summary: "講座情報を登録する。"
      description: >
        講座情報を登録する。
      security:
        -Bearer: []
      parameters:
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                  description: タイトル
                  example: '講座タイトル'
                image:
                  type: "file"
                  description: 画像ファイル
                  example: 'thumbnail.png'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                required:
                  - "result"
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
  /v1/instructor/course/{course_id}/chapter:
    post:
      tags:
        - instructor-course
      operationId: postInstructorChapter
      summary: "チャプター情報を登録する。"
      description: >
        チャプター情報を登録する。
      security:
        -Bearer: []
      parameters:
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                  description: タイトル
                  example: 'チャプタータイトル'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                required:
                  - "result"
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
  /v1/instructor/course/{course_id}/chapter/{chapter_id}:
    patch:
      tags:
        - instructor-course
      operationId: patchInstructorChapter
      summary: "チャプター情報を更新する。"
      description: >
        チャプター情報を更新する。
      security:
        -Bearer: []
      parameters:
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                  description: タイトル
                  example: 'チャプタータイトル'
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                required:
                  - "result"
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
    delete:
      tags:
        - instructor-course
      operationId: deleteInstructorChapter
      summary: "チャプター情報を削除する。"
      description: >
        チャプター情報を削除する。
      security:
        -Bearer: []
      parameters:
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                required:
                  - "result"
                type: "object"
                properties:
                  result:
                    type: "boolean"
                    example: true
components:
  securitySchemes:
        Bearer:
          type: apiKey
          in: header
          name: XSRF-TOKEN
          description: API認証トークン
  schemas:
    Instructor:
      type: "object"
      required:
        - "instructor_id"
        - "nick_name"
        - "last_name"
        - "first_name"
        - "email"
      properties:
        instructor_id:
          type: "int"
          description: "講師テーブル主キー"
          example: 1
        nick_name:
          type: "string"
          description: "ニックネーム"
          example: "タロー"
        last_name:
          type: "string"
          description: "性"
          example: "山田"
        first_name:
          type: "string"
          description: "名"
          example: "太郎"
        email:
          type: "string"
          description: "メールアドレス"
          example: "test@example.com"
    Course:
      type: "object"
      required:
        - "course_id"
        - "title"
        - "image"
        - "attendance"
      properties:
        course_id:
          type: "int"
          description: "講座テーブル主キー"
          example: 1
        title:
          type: "string"
          description: "講座名"
          example: "PHP入門講座"
        image:
          type: "string"
          description: "講座サムネイル画像ファイルパス"
          example: "/course/xxx.png"
    Attendance:
      type: "object"
      required:
        - "attendance_id"
        - "progress"
      properties:
        attendance_id:
          type: "int"
          description: "受講テーブル主キー"
          example: 1
        progress:
          type: "int"
          description: "進捗率"
          example: 70
    Chapter:
      type: "object" 
      required:
        - "chapter_id"
        - "title"
        - "lesson"
        - "order"
      properties:
        chapter_id:
          type: "int"
          description: "チャプターテーブルの主キー"
          example: 1
        title:
          type: "string"
          description: "チャプタータイトル"
          example: "laravel入門講座"
        order:
          type: "int"
          description: "順番"
          example: 1
    Lesson:
      type: "object"
      required:
        - "lesson_id"
        - "title"
        - "status"
        - "lesson_attendance"
        - "order"
      properties:
        lesson_id:
          type: "int"
          description: "レッスンテーブルの主キー"
          example: 1
        title:
          type: "string"
          description: "レッスン名"
          example: "swaggerの書き方"
        url:
          type: "string"
          description: "教材動画URL"
          example: "http::www.youtube"
        remarks:
          type: "string"
          description: "備考欄"
          example: "動画index"
        order:
          type: "int"
          description: "順番"
          example: 1
    LessonAttendance:
      type: "object"
      required:
        - "lesson_attendance_id"
        - "status"
      properties:
        lesson_attendance_id:
          type: "int"
          description: "レッスン受講テーブルの主キー"
          example: 1
        status:
          type: "string"
          description: "レッスン受講状態（未着手, 着手, 完了）"
          example: "before_attendance"