openapi: 3.0.0
info:
  version: 1.0.0
  title: 受講管理アプリ API
servers:
  - url: 'http://localhost:8080/api'
paths:
  /v1/courses:
    get:
      tags:
        - course
      operationId: getCourses
      summary: "受講講座一覧参照"
      description: >
        受講者IDを指定して、受講している講座一覧情報を参照する
      security: 
        - Bearer: []
      parameters:
        - name: student_id
          in: query
          description: 受講者テーブル主キー
          required: true
          type: int
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      responses:
        '200':
          description: 受講講座一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      allOf:
                        - $ref: '#/components/schemas/Course'
                        - type: "object"
                          properties:
                            attendance:
                              $ref: '#/components/schemas/Attendance'
  /v1/course:
    get:
      tags:
        - course
      operationId: getCourse
      summary: "講座詳細一覧参照"
      description: >
        受講者IDを指定して、受講している講座のチャプター一覧・進捗情報を参照する
      security:
        -Bearer: []
      parameters:
        - name: chapter_id
          in: query
          description: チャプターテーブルの主キー
          required: true
          type: int
        - name: attendance_id
          in: query
          description: 受講テーブルの主キー
          required: true
          type: int
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      responses:
        '200':
          description: 講座詳細情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  data: 
                    allOf:
                      - $ref: '#/components/schemas/Course'
                      - type: object
                        properties:
                          attendance:
                            $ref: '#/components/schemas/Attendance'
                      - type: object
                        properties:
                          chapters:
                            type: array
                            items:
                              allOf:
                                - $ref: '#/components/schemas/Chapter'
                                - type: object
                                  properties:
                                    lessons:
                                      type: array
                                      items:
                                        allOf:
                                          - $ref: '#/components/schemas/Lesson'
                                          - type: object
                                            properties:
                                              lesson_attendance:
                                                $ref: '#/components/schemas/LessonAttendance'
components:
  securitySchemes:
        Bearer:
          type: apiKey
          in: header
          name: XSRF-TOKEN
          description: API認証トークン
  schemas:
    Instructor:
      type: "object"
      required:
        - "instructor_id"
        - "name"
        - "email"
      properties:
        instructor_id:
          type: "int"
          description: "講師テーブル主キー"
          example: 1
        name:
          type: "string"
          description: "講師名"
          example: "山田 太郎"
        email:
          type: "string"
          description: "メールアドレス"
          example: "test@example.com"
    Course:
      type: "object"
      required:
        - "course_id"
        - "title"
        - "image"
        - "instructor"
        - "attendance"
      properties:
        course_id:
          type: "int"
          description: "講座テーブル主キー"
          example: 1
        title:
          type: "string"
          description: "講座名"
          example: "PHP入門講座"
        image:
          type: "string"
          description: "講座サムネイル画像ファイルパス"
          example: "/course/xxx.png"
        instructor:
          $ref: '#/components/schemas/Instructor'
    Attendance:
      type: "object"
      required:
        - "attendance_id"
        - "progress"
      properties:
        attendance_id:
          type: "int"
          description: "受講テーブル主キー"
          example: 1
        progress:
          type: "int"
          description: "進捗率"
          example: 70
    Chapter:
      type: "object" 
      required:
        - "chapter_id"
        - "title"
        - "lesson"
      properties:
        chapter_id:
          type: "int"
          description: "チャプターテーブルの主キー"
          example: 1
        title:
          type: "string"
          description: "チャプタータイトル"
          example: "laravel入門講座"
    Lesson:
      type: "object"
      required:
        - "lesson_id"
        - "title"
        - "status"
        - "lesson_attendance"
      properties:
        lesson_id:
          type: "int"
          description: "レッスンテーブルの主キー"
          example: 1
        title:
          type: "string"
          description: "レッスン名"
          example: "swaggerの書き方"
    LessonAttendance:
      type: "object"
      required:
        - "lesson_attendance_id"
        - "status"
      properties:
        lesson_attendance_id:
          type: "int"
          description: "レッスン受講テーブルの主キー"
          example: 1
        status:
          type: "tinyint"
          description: "10, 20, 30"
          example: "10"