openapi: 3.0.0
info:
  version: 1.0.0
  title: 受講管理アプリ API
servers:
  - url: 'http://localhost:8080/api'
paths:
  /v1/courses:
    get:
      tags:
        - course
      operationId: getCourses
      summary: "受講講座一覧参照"
      description: >
        受講者IDを指定して、受講している講座一覧情報を参照する
      security: 
        - Bearer: []
      parameters:
        - name: student_id
          in: quy
          description: 受講者テーブル主キー
          required: true
          type: int
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      responses:
        '200':
          description: 受講講座一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/Course'
                    - type: "object"
                      properties:
                        attendance:
                          $ref: '#/components/schemas/Attendance'
  /v1/chapters:
    get:
      tags:
        - chapter
      operationId: getChapters
      summary: "チャプター一覧参照"
      description: >
        受講者IDを指定して、受講している講座のチャプター一覧・進捗情報を参照する
      security:
        -Bearer: []
      parameters:
        - name: chapter_id
          in: query
          description: チャプターテーブルの主キー
          required: true
          type: int
        - name: attendances_id
          in: query
          description: 受講テーブルの主キー
          required: true
          type: int
        - name: XSRF-TOKEN
          in: header
          description: API認証トークン
          required: true
          type: string
      responses:
        '200':
          description: 講座詳細情報
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chapter'
components:
  securitySchemes:
        Bearer:
          type: apiKey
          in: header
          name: XSRF-TOKEN
          description: API認証トークン
  schemas:
    Instructor:
      type: "object"
      required:
        - "instructor_id"
        - "name"
        - "email"
      properties:
        instructor_id:
          type: "int"
          description: "講師テーブル主キー"
          example: 1
        name:
          type: "string"
          description: "講師名"
          example: "山田 太郎"
        email:
          type: "string"
          description: "メールアドレス"
          example: "test@example.com"
    Course:
      type: "object"
      required:
        - "course_id"
        - "title"
        - "image"
        - "instructor"
        - "attendance"
      properties:
        course_id:
          type: "int"
          description: "講座テーブル主キー"
          example: 1
        title:
          type: "string"
          description: "講座名"
          example: "PHP入門講座"
        image:
          type: "string"
          description: "講座サムネイル画像ファイルパス"
          example: "/course/xxx.png"
        instructor:
          $ref: '#/components/schemas/Instructor'
    Attendance:
      type: "object"
      required:
        - "attendance_id"
        - "progress"
      properties:
        attendance_id:
          type: "int"
          description: "受講テーブル主キー"
          example: 1
        progress:
          type: "int"
          description: "進捗率"
          example: 70
    Chapter:
      type: "object" 
      required:
        - "chapter_id"
        - "chapter_title"
        - "course"
        - "lesson"
        - "attendance"
        - "lesson_attendance"
      properties:
        course:
          $ref: '#/components/schemas/Course'
        chapter_id:
          type: "int"
          description: "チャプターテーブル主キー"
          example: 1
        chapter_title: 
          type: "string"
          description: "チャプター名"
          example: "laravel入門"
        lesson:
          $ref: '#/components/schemas/Lesson'
        attendance:
          $ref: '#/components/schemas/Attendance'
        lesson_attendance:
          $ref: '#/components/schemas/Lesson_attendance'
    Lesson:
      type: "object"
      required:
        - "lesson_id"
        - "title"
      properties:
        lesson_id:
          type: "int"
          description: "レッスンテーブルの主キー"
          example: 1
        title:
          type: "string"
          description: "レッスン名"
          example: "swaggerの書き方"
    Lesson_attendance:
      type: "object"
      required:
        - "lesson_attendance_id"
        - "status"
      properties:
        lesson_attendance_id:
          type: "int"
          description: "レッスン受講テーブルの主キー"
          example: 1
        status:
          type: "tinyint"
          description: "未着手、着手、完了"
          example: "未着手"